services:
    # FRONTEND
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        volumes:
            - ./web:/app
            - /app/node_modules
            - /app/.next
        environment:
            - WATCHPACK_POLLING=true
        networks:
            - omahtryout-network
    # auth service
    # Database for the auth service
    auth-service-db:
        image: postgres:17.2-alpine
        env_file:
            - auth-service/.env
        volumes:
            - ./auth-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql # init script
            - auth-data:/var/lib/postgresql/data
        networks:
            - omahtryout-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U omahTryOut -d auth_service_db"]
            interval: 5s
            timeout: 5s
            retries: 5

        # API for the auth service
    auth-service-api:
        build: ./auth-service
        env_file:
            - auth-service/.env
            - .env
        depends_on:
            auth-service-db:
                condition: service_healthy # Ensure DB is ready
        networks:
            - omahtryout-network
        ports:
            - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}

    # Soal service
    # Database for the soal service
    soal-service-db:
        image: postgres:17.2-alpine
        env_file:
            - soal-service/.env
        volumes:
            - ./soal-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql # init script
            - soal-data:/var/lib/postgresql/data
        networks:
            - omahtryout-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U omahTryOut -d soal_service_db"]
            interval: 5s
            timeout: 5s
            retries: 5

    # API for the soal service
    soal-service-api:
        build: ./soal-service
        env_file:
            - soal-service/.env
            - .env
        depends_on:
            soal-service-db:
                condition: service_healthy # Ensure DB is ready
        networks:
            - omahtryout-network
        ports:
            - ${SOAL_SERVICE_PORT}:${SOAL_SERVICE_PORT}

    # Tryout service
    # Database for the tryout service
    tryout-service-db:
        image: postgres:17.2-alpine
        env_file:
            - tryout-service/.env
        volumes:
            - ./tryout-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql # init script
            - tryout-data:/var/lib/postgresql/data
        networks:
            - omahtryout-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U omahTryOut -d tryout_service_db"]
            interval: 5s
            timeout: 5s
            retries: 5

    # API for the tryout service
    tryout-service-api:
        build: ./tryout-service
        env_file:
            - tryout-service/.env
            - .env
        depends_on:
            tryout-service-db:
                condition: service_healthy # Ensure DB is ready
        networks:
            - omahtryout-network
        ports:
            - ${TRYOUT_SERVICE_PORT}:${TRYOUT_SERVICE_PORT}

    # Minat bakat service
    minat-bakat-service-db:
        image: postgres:17.2-alpine
        env_file:
            - minat-bakat-service/.env
        volumes:
            - ./minat-bakat-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql # init script
            - minat-bakat-data:/var/lib/postgresql/data
        networks:
            - omahtryout-network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U omahTryOut -d minat-bakat_service_db",
                ]
            interval: 5s
            timeout: 5s
            retries: 5

    # API for the minat bakat service
    minat-bakat-service-api:
        build: ./minat-bakat-service
        env_file:
            - minat-bakat-service/.env
            - .env
        depends_on:
            minat-bakat-service-db:
                condition: service_healthy # Ensure DB is ready
        networks:
            - omahtryout-network
        ports:
            - ${MINAT_BAKAT_SERVICE_PORT}:${MINAT_BAKAT_SERVICE_PORT}

networks:
    omahtryout-network:

# volumes for persistent data
volumes:
    auth-data:
    soal-data:
    tryout-data:
    minat-bakat-data:
