global:
  scrape_interval: 15s  # How often to collect metrics
  evaluation_interval: 15s  # Rule evaluation frequency

scrape_configs:
  # Monitor Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # Loki Metrics
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']  # Loki metrics endpoint
      
  # Auth Service Metrics
  - job_name: auth-service
    static_configs:
      - targets: ['auth-service-api:8081']  # Your service's metrics port
    metrics_path: /metrics  # Default endpoint

  # Soal Service Metrics
  - job_name: soal-service
    static_configs:
      - targets: ['soal-service-api:8082']  # Your service's metrics port
    metrics_path: /metrics  # Default endpoint

  # Tryout Service Metrics
  - job_name: tryout-service
    static_configs:
      - targets: ['tryout-service-api:8083']  # Your service's metrics port
    metrics_path: /metrics  # Default endpoint

    # Minat Bakat Service Metrics
  - job_name: minat-bakat-service
    static_configs:
      - targets: ['minat-bakat-service-api:8084']  # Your service's metrics port
    metrics_path: /metrics  # Default endpoint

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
    - targets: ['traefik:80']
