entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    watch: true
    network: "omahtryout-network"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true
  insecure: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/_wildcard.omahto.localhost+1.pem
        keyFile: /certs/_wildcard.omahto.localhost-key+1.pem
