// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: soal/soal.proto

package soal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAnswerKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaketSoal     string                 `protobuf:"bytes,1,opt,name=paket_soal,json=paketSoal,proto3" json:"paket_soal,omitempty"`
	Subtest       string                 `protobuf:"bytes,2,opt,name=subtest,proto3" json:"subtest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswerKeyRequest) Reset() {
	*x = GetAnswerKeyRequest{}
	mi := &file_soal_soal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswerKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerKeyRequest) ProtoMessage() {}

func (x *GetAnswerKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soal_soal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAnswerKeyRequest) Descriptor() ([]byte, []int) {
	return file_soal_soal_proto_rawDescGZIP(), []int{0}
}

func (x *GetAnswerKeyRequest) GetPaketSoal() string {
	if x != nil {
		return x.PaketSoal
	}
	return ""
}

func (x *GetAnswerKeyRequest) GetSubtest() string {
	if x != nil {
		return x.Subtest
	}
	return ""
}

type GetAnswerKeyResponse struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	PilihanGandaAnswers map[string]*PilihanGandaMap `protobuf:"bytes,1,rep,name=pilihan_ganda_answers,json=pilihanGandaAnswers,proto3" json:"pilihan_ganda_answers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TrueFalseAnswers    map[string]*TrueFalseAnswer `protobuf:"bytes,2,rep,name=true_false_answers,json=trueFalseAnswers,proto3" json:"true_false_answers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UraianAnswers       map[string]*UraianAnswer    `protobuf:"bytes,3,rep,name=uraian_answers,json=uraianAnswers,proto3" json:"uraian_answers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAnswerKeyResponse) Reset() {
	*x = GetAnswerKeyResponse{}
	mi := &file_soal_soal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswerKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerKeyResponse) ProtoMessage() {}

func (x *GetAnswerKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soal_soal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAnswerKeyResponse) Descriptor() ([]byte, []int) {
	return file_soal_soal_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnswerKeyResponse) GetPilihanGandaAnswers() map[string]*PilihanGandaMap {
	if x != nil {
		return x.PilihanGandaAnswers
	}
	return nil
}

func (x *GetAnswerKeyResponse) GetTrueFalseAnswers() map[string]*TrueFalseAnswer {
	if x != nil {
		return x.TrueFalseAnswers
	}
	return nil
}

func (x *GetAnswerKeyResponse) GetUraianAnswers() map[string]*UraianAnswer {
	if x != nil {
		return x.UraianAnswers
	}
	return nil
}

type PilihanGandaMap struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Choices       map[string]*PilihanGandaChoice `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PilihanGandaMap) Reset() {
	*x = PilihanGandaMap{}
	mi := &file_soal_soal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PilihanGandaMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PilihanGandaMap) ProtoMessage() {}

func (x *PilihanGandaMap) ProtoReflect() protoreflect.Message {
	mi := &file_soal_soal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PilihanGandaMap.ProtoReflect.Descriptor instead.
func (*PilihanGandaMap) Descriptor() ([]byte, []int) {
	return file_soal_soal_proto_rawDescGZIP(), []int{2}
}

func (x *PilihanGandaMap) GetChoices() map[string]*PilihanGandaChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

type PilihanGandaChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCorrect     bool                   `protobuf:"varint,1,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Bobot         int32                  `protobuf:"varint,2,opt,name=bobot,proto3" json:"bobot,omitempty"`
	TextPilihan   string                 `protobuf:"bytes,3,opt,name=text_pilihan,json=textPilihan,proto3" json:"text_pilihan,omitempty"`
	Pembahasan    string                 `protobuf:"bytes,4,opt,name=pembahasan,proto3" json:"pembahasan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PilihanGandaChoice) Reset() {
	*x = PilihanGandaChoice{}
	mi := &file_soal_soal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PilihanGandaChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PilihanGandaChoice) ProtoMessage() {}

func (x *PilihanGandaChoice) ProtoReflect() protoreflect.Message {
	mi := &file_soal_soal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PilihanGandaChoice.ProtoReflect.Descriptor instead.
func (*PilihanGandaChoice) Descriptor() ([]byte, []int) {
	return file_soal_soal_proto_rawDescGZIP(), []int{3}
}

func (x *PilihanGandaChoice) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *PilihanGandaChoice) GetBobot() int32 {
	if x != nil {
		return x.Bobot
	}
	return 0
}

func (x *PilihanGandaChoice) GetTextPilihan() string {
	if x != nil {
		return x.TextPilihan
	}
	return ""
}

func (x *PilihanGandaChoice) GetPembahasan() string {
	if x != nil {
		return x.Pembahasan
	}
	return ""
}

type TrueFalseAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jawaban       string                 `protobuf:"bytes,1,opt,name=jawaban,proto3" json:"jawaban,omitempty"`
	Bobot         int32                  `protobuf:"varint,2,opt,name=bobot,proto3" json:"bobot,omitempty"`
	TextPilihan   string                 `protobuf:"bytes,3,opt,name=text_pilihan,json=textPilihan,proto3" json:"text_pilihan,omitempty"`
	Pembahasan    string                 `protobuf:"bytes,4,opt,name=pembahasan,proto3" json:"pembahasan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrueFalseAnswer) Reset() {
	*x = TrueFalseAnswer{}
	mi := &file_soal_soal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrueFalseAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrueFalseAnswer) ProtoMessage() {}

func (x *TrueFalseAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_soal_soal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrueFalseAnswer.ProtoReflect.Descriptor instead.
func (*TrueFalseAnswer) Descriptor() ([]byte, []int) {
	return file_soal_soal_proto_rawDescGZIP(), []int{4}
}

func (x *TrueFalseAnswer) GetJawaban() string {
	if x != nil {
		return x.Jawaban
	}
	return ""
}

func (x *TrueFalseAnswer) GetBobot() int32 {
	if x != nil {
		return x.Bobot
	}
	return 0
}

func (x *TrueFalseAnswer) GetTextPilihan() string {
	if x != nil {
		return x.TextPilihan
	}
	return ""
}

func (x *TrueFalseAnswer) GetPembahasan() string {
	if x != nil {
		return x.Pembahasan
	}
	return ""
}

type UraianAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jawaban       string                 `protobuf:"bytes,1,opt,name=jawaban,proto3" json:"jawaban,omitempty"`
	Bobot         int32                  `protobuf:"varint,2,opt,name=bobot,proto3" json:"bobot,omitempty"`
	Pembahasan    string                 `protobuf:"bytes,3,opt,name=pembahasan,proto3" json:"pembahasan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UraianAnswer) Reset() {
	*x = UraianAnswer{}
	mi := &file_soal_soal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UraianAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UraianAnswer) ProtoMessage() {}

func (x *UraianAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_soal_soal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UraianAnswer.ProtoReflect.Descriptor instead.
func (*UraianAnswer) Descriptor() ([]byte, []int) {
	return file_soal_soal_proto_rawDescGZIP(), []int{5}
}

func (x *UraianAnswer) GetJawaban() string {
	if x != nil {
		return x.Jawaban
	}
	return ""
}

func (x *UraianAnswer) GetBobot() int32 {
	if x != nil {
		return x.Bobot
	}
	return 0
}

func (x *UraianAnswer) GetPembahasan() string {
	if x != nil {
		return x.Pembahasan
	}
	return ""
}

var File_soal_soal_proto protoreflect.FileDescriptor

const file_soal_soal_proto_rawDesc = "" +
	"\n" +
	"\x0fsoal/soal.proto\x12\x04soal\"N\n" +
	"\x13GetAnswerKeyRequest\x12\x1d\n" +
	"\n" +
	"paket_soal\x18\x01 \x01(\tR\tpaketSoal\x12\x18\n" +
	"\asubtest\x18\x02 \x01(\tR\asubtest\"\xc6\x04\n" +
	"\x14GetAnswerKeyResponse\x12g\n" +
	"\x15pilihan_ganda_answers\x18\x01 \x03(\v23.soal.GetAnswerKeyResponse.PilihanGandaAnswersEntryR\x13pilihanGandaAnswers\x12^\n" +
	"\x12true_false_answers\x18\x02 \x03(\v20.soal.GetAnswerKeyResponse.TrueFalseAnswersEntryR\x10trueFalseAnswers\x12T\n" +
	"\x0euraian_answers\x18\x03 \x03(\v2-.soal.GetAnswerKeyResponse.UraianAnswersEntryR\ruraianAnswers\x1a]\n" +
	"\x18PilihanGandaAnswersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.soal.PilihanGandaMapR\x05value:\x028\x01\x1aZ\n" +
	"\x15TrueFalseAnswersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.soal.TrueFalseAnswerR\x05value:\x028\x01\x1aT\n" +
	"\x12UraianAnswersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.soal.UraianAnswerR\x05value:\x028\x01\"\xa5\x01\n" +
	"\x0fPilihanGandaMap\x12<\n" +
	"\achoices\x18\x01 \x03(\v2\".soal.PilihanGandaMap.ChoicesEntryR\achoices\x1aT\n" +
	"\fChoicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.soal.PilihanGandaChoiceR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x12PilihanGandaChoice\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x01 \x01(\bR\tisCorrect\x12\x14\n" +
	"\x05bobot\x18\x02 \x01(\x05R\x05bobot\x12!\n" +
	"\ftext_pilihan\x18\x03 \x01(\tR\vtextPilihan\x12\x1e\n" +
	"\n" +
	"pembahasan\x18\x04 \x01(\tR\n" +
	"pembahasan\"\x84\x01\n" +
	"\x0fTrueFalseAnswer\x12\x18\n" +
	"\ajawaban\x18\x01 \x01(\tR\ajawaban\x12\x14\n" +
	"\x05bobot\x18\x02 \x01(\x05R\x05bobot\x12!\n" +
	"\ftext_pilihan\x18\x03 \x01(\tR\vtextPilihan\x12\x1e\n" +
	"\n" +
	"pembahasan\x18\x04 \x01(\tR\n" +
	"pembahasan\"^\n" +
	"\fUraianAnswer\x12\x18\n" +
	"\ajawaban\x18\x01 \x01(\tR\ajawaban\x12\x14\n" +
	"\x05bobot\x18\x02 \x01(\x05R\x05bobot\x12\x1e\n" +
	"\n" +
	"pembahasan\x18\x03 \x01(\tR\n" +
	"pembahasan2T\n" +
	"\vSoalService\x12E\n" +
	"\fGetAnswerKey\x12\x19.soal.GetAnswerKeyRequest\x1a\x1a.soal.GetAnswerKeyResponseB?Z=github.com/vityasyyy/omah-to/soal-service/internal/proto/soalb\x06proto3"

var (
	file_soal_soal_proto_rawDescOnce sync.Once
	file_soal_soal_proto_rawDescData []byte
)

func file_soal_soal_proto_rawDescGZIP() []byte {
	file_soal_soal_proto_rawDescOnce.Do(func() {
		file_soal_soal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_soal_soal_proto_rawDesc), len(file_soal_soal_proto_rawDesc)))
	})
	return file_soal_soal_proto_rawDescData
}

var file_soal_soal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_soal_soal_proto_goTypes = []any{
	(*GetAnswerKeyRequest)(nil),  // 0: soal.GetAnswerKeyRequest
	(*GetAnswerKeyResponse)(nil), // 1: soal.GetAnswerKeyResponse
	(*PilihanGandaMap)(nil),      // 2: soal.PilihanGandaMap
	(*PilihanGandaChoice)(nil),   // 3: soal.PilihanGandaChoice
	(*TrueFalseAnswer)(nil),      // 4: soal.TrueFalseAnswer
	(*UraianAnswer)(nil),         // 5: soal.UraianAnswer
	nil,                          // 6: soal.GetAnswerKeyResponse.PilihanGandaAnswersEntry
	nil,                          // 7: soal.GetAnswerKeyResponse.TrueFalseAnswersEntry
	nil,                          // 8: soal.GetAnswerKeyResponse.UraianAnswersEntry
	nil,                          // 9: soal.PilihanGandaMap.ChoicesEntry
}
var file_soal_soal_proto_depIdxs = []int32{
	6, // 0: soal.GetAnswerKeyResponse.pilihan_ganda_answers:type_name -> soal.GetAnswerKeyResponse.PilihanGandaAnswersEntry
	7, // 1: soal.GetAnswerKeyResponse.true_false_answers:type_name -> soal.GetAnswerKeyResponse.TrueFalseAnswersEntry
	8, // 2: soal.GetAnswerKeyResponse.uraian_answers:type_name -> soal.GetAnswerKeyResponse.UraianAnswersEntry
	9, // 3: soal.PilihanGandaMap.choices:type_name -> soal.PilihanGandaMap.ChoicesEntry
	2, // 4: soal.GetAnswerKeyResponse.PilihanGandaAnswersEntry.value:type_name -> soal.PilihanGandaMap
	4, // 5: soal.GetAnswerKeyResponse.TrueFalseAnswersEntry.value:type_name -> soal.TrueFalseAnswer
	5, // 6: soal.GetAnswerKeyResponse.UraianAnswersEntry.value:type_name -> soal.UraianAnswer
	3, // 7: soal.PilihanGandaMap.ChoicesEntry.value:type_name -> soal.PilihanGandaChoice
	0, // 8: soal.SoalService.GetAnswerKey:input_type -> soal.GetAnswerKeyRequest
	1, // 9: soal.SoalService.GetAnswerKey:output_type -> soal.GetAnswerKeyResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_soal_soal_proto_init() }
func file_soal_soal_proto_init() {
	if File_soal_soal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_soal_soal_proto_rawDesc), len(file_soal_soal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_soal_soal_proto_goTypes,
		DependencyIndexes: file_soal_soal_proto_depIdxs,
		MessageInfos:      file_soal_soal_proto_msgTypes,
	}.Build()
	File_soal_soal_proto = out.File
	file_soal_soal_proto_goTypes = nil
	file_soal_soal_proto_depIdxs = nil
}
