server:
  http_listen_port: 9080  # Promtail's own metrics endpoint

clients:
  - url: http://loki:3100/loki/api/v1/push  # Send logs to Loki

positions:
  filename: /tmp/positions.yaml  # Track log read positions

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            layer: layer
            operation: operation
            message: message
      - labels:
          level:
          service:
          layer:
          operation:

    relabel_configs:
      # Extract container name
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container

      # Set job from docker compose service name
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: job

      # Add container ID
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      # Map container log file path
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/${1}/*.log
