// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: soal/soal.proto

package soal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SoalService_GetAnswerKey_FullMethodName = "/soal.SoalService/GetAnswerKey"
)

// SoalServiceClient is the client API for SoalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoalServiceClient interface {
	GetAnswerKey(ctx context.Context, in *GetAnswerKeyRequest, opts ...grpc.CallOption) (*GetAnswerKeyResponse, error)
}

type soalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoalServiceClient(cc grpc.ClientConnInterface) SoalServiceClient {
	return &soalServiceClient{cc}
}

func (c *soalServiceClient) GetAnswerKey(ctx context.Context, in *GetAnswerKeyRequest, opts ...grpc.CallOption) (*GetAnswerKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnswerKeyResponse)
	err := c.cc.Invoke(ctx, SoalService_GetAnswerKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoalServiceServer is the server API for SoalService service.
// All implementations must embed UnimplementedSoalServiceServer
// for forward compatibility.
type SoalServiceServer interface {
	GetAnswerKey(context.Context, *GetAnswerKeyRequest) (*GetAnswerKeyResponse, error)
	mustEmbedUnimplementedSoalServiceServer()
}

// UnimplementedSoalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSoalServiceServer struct{}

func (UnimplementedSoalServiceServer) GetAnswerKey(context.Context, *GetAnswerKeyRequest) (*GetAnswerKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnswerKey not implemented")
}
func (UnimplementedSoalServiceServer) mustEmbedUnimplementedSoalServiceServer() {}
func (UnimplementedSoalServiceServer) testEmbeddedByValue()                     {}

// UnsafeSoalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoalServiceServer will
// result in compilation errors.
type UnsafeSoalServiceServer interface {
	mustEmbedUnimplementedSoalServiceServer()
}

func RegisterSoalServiceServer(s grpc.ServiceRegistrar, srv SoalServiceServer) {
	// If the following call pancis, it indicates UnimplementedSoalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SoalService_ServiceDesc, srv)
}

func _SoalService_GetAnswerKey_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetAnswerKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoalServiceServer).GetAnswerKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SoalService_GetAnswerKey_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(SoalServiceServer).GetAnswerKey(ctx, req.(*GetAnswerKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SoalService_ServiceDesc is the grpc.ServiceDesc for SoalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "soal.SoalService",
	HandlerType: (*SoalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnswerKey",
			Handler:    _SoalService_GetAnswerKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "soal/soal.proto",
}
